-- 0001_init.sql — initial schema matching db/schema.sql
BEGIN;

-- ============================================================
-- Provenance and review tables
-- ============================================================

CREATE TABLE data_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    source_kind text NOT NULL CHECK (source_kind IN ('official', 'supporting', 'artifact', 'internal')),
    base_url text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ingestion_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id bigint REFERENCES data_source(id),
    run_type text NOT NULL CHECK (run_type IN ('ingest', 'recompute', 'export')),
    status text NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'skipped')),
    started_at timestamptz,
    finished_at timestamptz,
    record_count integer NOT NULL DEFAULT 0 CHECK (record_count >= 0),
    error_message text,
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE source_artifact (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id bigint NOT NULL REFERENCES data_source(id),
    ingestion_run_id bigint REFERENCES ingestion_run(id),
    artifact_kind text NOT NULL CHECK (artifact_kind IN ('pdf', 'xml', 'csv', 'json', 'html', 'txt', 'other')),
    source_url text,
    storage_uri text NOT NULL UNIQUE,
    sha256 char(64) NOT NULL UNIQUE,
    mime_type text,
    fetched_at timestamptz,
    is_immutable boolean NOT NULL DEFAULT true,
    source_record_id text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parse_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingestion_run_id bigint REFERENCES ingestion_run(id),
    source_artifact_id bigint NOT NULL REFERENCES source_artifact(id) ON DELETE CASCADE,
    parser_name text NOT NULL,
    parser_version text NOT NULL,
    status text NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'skipped')),
    page_count integer CHECK (page_count IS NULL OR page_count >= 0),
    ocr_page_count integer CHECK (ocr_page_count IS NULL OR ocr_page_count >= 0),
    confidence_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_message text,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at),
    UNIQUE (source_artifact_id, parser_name, parser_version)
);

CREATE TABLE match_decision (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingestion_run_id bigint REFERENCES ingestion_run(id),
    parse_run_id bigint NOT NULL REFERENCES parse_run(id) ON DELETE CASCADE,
    subject_type text NOT NULL,
    subject_key text NOT NULL,
    candidate_type text NOT NULL,
    candidate_key text NOT NULL,
    confidence_label text NOT NULL CHECK (confidence_label IN ('HIGH', 'MEDIUM', 'LOW')),
    decision text NOT NULL CHECK (decision IN ('accept', 'reject', 'defer')),
    notes text,
    signals jsonb NOT NULL DEFAULT '{}'::jsonb,
    decided_by text,
    decided_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (parse_run_id, subject_type, subject_key, candidate_type, candidate_key)
);

CREATE TABLE review_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingestion_run_id bigint REFERENCES ingestion_run(id),
    parse_run_id bigint REFERENCES parse_run(id) ON DELETE CASCADE,
    source_artifact_id bigint REFERENCES source_artifact(id),
    review_type text NOT NULL,
    entity_type text NOT NULL,
    entity_key text NOT NULL,
    priority integer NOT NULL DEFAULT 100 CHECK (priority BETWEEN 1 AND 100),
    status text NOT NULL CHECK (status IN ('open', 'in_review', 'resolved', 'dismissed')),
    reason_code text NOT NULL,
    summary text,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    assigned_to text,
    reviewed_by text,
    reviewed_at timestamptz,
    decision text CHECK (decision IN ('accept', 'reject', 'defer')),
    decision_notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_review_queue_status ON review_queue (status);

-- ============================================================
-- Core canonical tables
-- ============================================================

CREATE TABLE member (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    bioguide_id text NOT NULL UNIQUE,
    lis_member_id text UNIQUE,
    fec_candidate_id text UNIQUE,
    slug text NOT NULL UNIQUE,
    first_name text,
    middle_name text,
    last_name text NOT NULL,
    full_name text NOT NULL,
    party text,
    state char(2),
    chamber text NOT NULL CHECK (chamber IN ('house', 'senate')),
    current_term_start date,
    current_term_end date,
    is_current boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (current_term_end IS NULL OR current_term_start IS NULL OR current_term_end >= current_term_start)
);

CREATE INDEX idx_member_is_current ON member (is_current) WHERE is_current;

CREATE TABLE member_term (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    congress integer NOT NULL CHECK (congress > 0),
    chamber text NOT NULL CHECK (chamber IN ('house', 'senate')),
    state char(2),
    district integer CHECK (district IS NULL OR district > 0),
    start_date date NOT NULL,
    end_date date,
    is_current boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date IS NULL OR end_date >= start_date),
    UNIQUE (member_id, congress, chamber, start_date)
);

CREATE TABLE committee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    committee_code text NOT NULL,
    congress integer NOT NULL CHECK (congress > 0),
    chamber text NOT NULL CHECK (chamber IN ('house', 'senate', 'joint')),
    committee_type text NOT NULL CHECK (committee_type IN ('standing', 'select', 'joint', 'subcommittee', 'other')),
    name text NOT NULL,
    parent_committee_id bigint REFERENCES committee(id) ON DELETE SET NULL,
    jurisdiction_basis text,
    review_tier text NOT NULL CHECK (review_tier IN ('deterministic', 'review_required', 'out_of_scope')),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (congress, committee_code)
);

CREATE TABLE committee_membership (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    committee_id bigint NOT NULL REFERENCES committee(id) ON DELETE CASCADE,
    member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    role text NOT NULL,
    start_date date NOT NULL,
    end_date date,
    is_current boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date IS NULL OR end_date >= start_date),
    UNIQUE (committee_id, member_id, start_date)
);

CREATE INDEX idx_committee_membership_member ON committee_membership (member_id);

CREATE TABLE bill (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    congress integer NOT NULL CHECK (congress > 0),
    bill_type text NOT NULL CHECK (bill_type IN ('hr', 's', 'hjres', 'sjres', 'hconres', 'sconres', 'hres', 'sres')),
    bill_number integer NOT NULL CHECK (bill_number > 0),
    title text NOT NULL,
    short_title text,
    introduced_date date,
    latest_action_date date,
    current_status text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (latest_action_date IS NULL OR introduced_date IS NULL OR latest_action_date >= introduced_date),
    UNIQUE (congress, bill_type, bill_number)
);

CREATE TABLE bill_sponsor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id bigint NOT NULL REFERENCES bill(id) ON DELETE CASCADE,
    member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    sponsor_role text NOT NULL CHECK (sponsor_role IN ('primary', 'cosponsor', 'original_cosponsor')),
    is_primary boolean NOT NULL DEFAULT false,
    sponsor_date date,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (bill_id, member_id)
);

CREATE INDEX idx_bill_sponsor_member ON bill_sponsor (member_id);

CREATE TABLE vote_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    chamber text NOT NULL CHECK (chamber IN ('house', 'senate')),
    congress integer NOT NULL CHECK (congress > 0),
    session_number integer NOT NULL CHECK (session_number > 0),
    roll_call_number integer NOT NULL CHECK (roll_call_number > 0),
    vote_date date NOT NULL,
    question text NOT NULL,
    result text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (chamber, congress, session_number, roll_call_number)
);

CREATE TABLE vote_cast (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_event_id bigint NOT NULL REFERENCES vote_event(id) ON DELETE CASCADE,
    member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    vote_option text NOT NULL CHECK (vote_option IN ('yea', 'nay', 'present', 'not_voting', 'paired', 'abstain')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (vote_event_id, member_id)
);

CREATE INDEX idx_vote_cast_member ON vote_cast (member_id);

CREATE TABLE fec_committee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    fec_committee_id text NOT NULL UNIQUE,
    committee_name text NOT NULL,
    committee_type text,
    designation_code text,
    treasurer_name text,
    city text,
    state char(2),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contribution (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint NOT NULL REFERENCES source_artifact(id) ON DELETE CASCADE,
    source_record_id text,
    recipient_fec_committee_id bigint REFERENCES fec_committee(id),
    source_fec_committee_id bigint REFERENCES fec_committee(id),
    donor_name text NOT NULL,
    donor_type text CHECK (donor_type IN ('individual', 'committee', 'organization', 'other')),
    contribution_type text CHECK (contribution_type IN ('contribution', 'refund', 'transfer', 'in_kind', 'other')),
    contribution_date date NOT NULL,
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    memo text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_contribution_recipient ON contribution (recipient_fec_committee_id);

CREATE TABLE financial_disclosure (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    chamber text NOT NULL CHECK (chamber IN ('house', 'senate')),
    filing_year integer NOT NULL CHECK (filing_year >= 1900),
    filing_type text NOT NULL CHECK (filing_type IN ('annual', 'ptr', 'amendment')),
    filing_period_start date,
    filing_period_end date,
    filed_at date,
    amendment_number integer NOT NULL DEFAULT 0 CHECK (amendment_number >= 0),
    is_amended boolean NOT NULL DEFAULT false,
    supersedes_financial_disclosure_id bigint REFERENCES financial_disclosure(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (filing_period_end IS NULL OR filing_period_start IS NULL OR filing_period_end >= filing_period_start),
    UNIQUE (member_id, filing_year, filing_type, amendment_number)
);

CREATE INDEX idx_financial_disclosure_member ON financial_disclosure (member_id);

CREATE TABLE holding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    financial_disclosure_id bigint NOT NULL REFERENCES financial_disclosure(id) ON DELETE CASCADE,
    line_number integer NOT NULL CHECK (line_number > 0),
    owner_type text NOT NULL CHECK (owner_type IN ('self', 'spouse', 'joint', 'dependent', 'trust', 'other')),
    issuer_name text NOT NULL,
    issuer_ticker text,
    asset_description text,
    asset_category text,
    value_min numeric(14,2),
    value_max numeric(14,2),
    value_label text,
    income_min numeric(14,2),
    income_max numeric(14,2),
    income_label text,
    is_liquid boolean,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (value_min IS NULL OR value_min >= 0),
    CHECK (value_max IS NULL OR value_max >= 0),
    CHECK (income_min IS NULL OR income_min >= 0),
    CHECK (income_max IS NULL OR income_max >= 0),
    CHECK (value_min IS NULL OR value_max IS NULL OR value_max >= value_min),
    CHECK (income_min IS NULL OR income_max IS NULL OR income_max >= income_min),
    UNIQUE (financial_disclosure_id, line_number)
);

CREATE TABLE "transaction" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    financial_disclosure_id bigint NOT NULL REFERENCES financial_disclosure(id) ON DELETE CASCADE,
    line_number integer NOT NULL CHECK (line_number > 0),
    owner_type text NOT NULL CHECK (owner_type IN ('self', 'spouse', 'joint', 'dependent', 'trust', 'other')),
    issuer_name text NOT NULL,
    issuer_ticker text,
    asset_description text,
    transaction_type text NOT NULL CHECK (transaction_type IN ('purchase', 'sale', 'exchange', 'gift', 'income', 'other')),
    transaction_date date NOT NULL,
    amount_min numeric(14,2),
    amount_max numeric(14,2),
    amount_label text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (amount_min IS NULL OR amount_min >= 0),
    CHECK (amount_max IS NULL OR amount_max >= 0),
    CHECK (amount_min IS NULL OR amount_max IS NULL OR amount_max >= amount_min),
    UNIQUE (financial_disclosure_id, line_number)
);

-- ============================================================
-- Scoring tables (rule_fire, evidence_card, score_snapshot)
-- ============================================================

CREATE TABLE rule_fire (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    recompute_run_id bigint NOT NULL REFERENCES ingestion_run(id),
    subject_member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    trigger_financial_disclosure_id bigint REFERENCES financial_disclosure(id) ON DELETE SET NULL,
    superseded_financial_disclosure_id bigint REFERENCES financial_disclosure(id) ON DELETE SET NULL,
    rule_id text NOT NULL,
    dimension text NOT NULL,
    rule_version text NOT NULL,
    severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
    source_facts jsonb NOT NULL DEFAULT '[]'::jsonb,
    derived_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    conditions jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_types_required text[] NOT NULL DEFAULT '{}'::text[],
    explanation text NOT NULL,
    fired_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (cardinality(source_types_required) > 0)
);

CREATE INDEX idx_rule_fire_member ON rule_fire (subject_member_id);
CREATE INDEX idx_rule_fire_recompute ON rule_fire (recompute_run_id);
CREATE INDEX idx_rule_fire_rule_id ON rule_fire (rule_id);

CREATE TABLE evidence_card (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    rule_fire_id bigint REFERENCES rule_fire(id) ON DELETE SET NULL,
    public_id text NOT NULL UNIQUE,
    member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    dimension text NOT NULL,
    score_delta numeric(10,2) NOT NULL,
    short_explanation text NOT NULL,
    source_anchors jsonb NOT NULL DEFAULT '[]'::jsonb,
    facts jsonb NOT NULL DEFAULT '{}'::jsonb,
    inferences jsonb NOT NULL DEFAULT '{}'::jsonb,
    normative_judgments jsonb NOT NULL DEFAULT '{}'::jsonb,
    confidence_label text NOT NULL CHECK (confidence_label IN ('HIGH', 'MEDIUM', 'LOW')),
    member_page_slug text,
    rendered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_evidence_card_member ON evidence_card (member_id);

CREATE TABLE score_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_artifact_id bigint REFERENCES source_artifact(id),
    source_record_id text,
    recompute_run_id bigint REFERENCES ingestion_run(id),
    member_id bigint NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    snapshot_at date NOT NULL,
    score_total numeric(10,2) NOT NULL,
    dimension_scores jsonb NOT NULL DEFAULT '{}'::jsonb,
    published_manifest_sha256 char(64),
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (member_id, snapshot_at)
);

COMMIT;
