"""Operator command execution and CLI dispatch helpers.

Split from the original monolithic ``commands.py``; this package re-exports
every top-level symbol (including the monolith's imported dependency names)
so all historical import paths keep working.
"""

# ruff: noqa: F401 -- this file IS the re-export surface; aliased names
# (e.g. ``dt``, ``_verify_roundtrip``) are part of the historical namespace.

from __future__ import annotations

import sys as _sys
import types as _types

import csv as csv
import datetime as dt
import hashlib as hashlib
import json as json
import math as math
import os as os
import re as re
import shlex as shlex
import shutil as shutil
import sys as sys
from collections.abc import Callable as Callable
from dataclasses import asdict as asdict, replace as replace
from pathlib import Path as Path
from src.evidence.source_anchor_policy import (
    has_official_claim_source_anchor as has_official_claim_source_anchor,
    is_official_source_url as is_official_source_url,
)
from src.ingest.congress.archive import (
    CongressArchive as CongressArchive,
    manifest_from_existing_archive as manifest_from_existing_archive,
)
from src.ingest.congress.archive_manifest import (
    load_manifest as load_congress_archive_manifest,
    write_manifest as write_manifest,
)
from src.ingest.congress.archive_validate import (
    validate_congress_archive_manifest as validate_congress_archive_manifest,
)
from src.parse.disclosures.transform import DisclosureTransformResult as DisclosureTransformResult
from src.pipeline.publish_snapshot_run import (
    ZipBundleInputs as ZipBundleInputs,
    _ontology_edge_from_row as _ontology_edge_from_row,
)
from src.prediction.backtest import (
    PredictionBacktestPayload as PredictionBacktestPayload,
    REQUIRED_ONTOLOGY_FEATURE_SIGNAL_NAMES as REQUIRED_ONTOLOGY_FEATURE_SIGNAL_NAMES,
)
from src.prediction.dataset import PredictionEvalDatasetPayload as PredictionEvalDatasetPayload
from src.prediction.eval_report import (
    PredictionEvalReportPayload as PredictionEvalReportPayload,
    build_prediction_eval_report as build_prediction_eval_report,
)
from src.prediction.llm_semantics import (
    BillSemanticIndexPayload as BillSemanticIndexPayload,
    OpenAIBillSemanticExtractor as OpenAIBillSemanticExtractor,
    bill_semantic_input_from_row as bill_semantic_input_from_row,
    load_bill_semantic_payloads as load_bill_semantic_payloads,
    materialize_bill_semantics as materialize_bill_semantics,
)
from src.prediction.window_plan import (
    PredictionEvalWindowPlanPayload as PredictionEvalWindowPlanPayload,
    build_prediction_eval_window_plan as build_prediction_eval_window_plan,
)
from src.query.published_rows import (
    fetch_all_ontology_edge_rows as fetch_all_ontology_edge_rows,
    fetch_bill_semantic_input_rows as fetch_bill_semantic_input_rows,
    fetch_vote_prediction_backtest_bill_signal_rows as fetch_vote_prediction_backtest_bill_signal_rows,
    fetch_vote_prediction_backtest_feature_rows as fetch_vote_prediction_backtest_feature_rows,
    fetch_vote_prediction_backtest_label_rows as fetch_vote_prediction_backtest_label_rows,
    fetch_vote_prediction_contribution_signal_rows as fetch_vote_prediction_contribution_signal_rows,
    fetch_vote_prediction_statement_signal_rows as fetch_vote_prediction_statement_signal_rows,
)
from src.runtime.app import (
    PsephosAmericaRuntime as PsephosAmericaRuntime,
    build_runtime as build_runtime,
    open_runtime_connection as open_runtime_connection,
)
from src.runtime.bill_semantics_cache import (
    bill_semantics_cache_failures as _prediction_backtest_bill_semantics_cache_failures,
    bill_semantics_index_model_names as _bill_semantics_index_model_names,
    bill_semantics_index_object as _bill_semantics_index_object,
    bill_semantics_index_payload as _bill_semantics_index_payload,
    bill_semantics_index_run_metadata_failures as _bill_semantics_index_run_metadata_failures,
    bill_semantics_index_sha256 as _bill_semantics_index_sha256,
)
from src.runtime.bootstrap import (
    bootstrap_database as bootstrap_database,
    describe_bootstrap_plan as describe_bootstrap_plan,
)
from src.runtime.congress import CongressLoadResult as CongressLoadResult
from src.runtime.congress_archive import run_congress_archive_load as run_congress_archive_load
from src.runtime.congress_archive_materialize import (
    MaterializedCongressArchiveResult as MaterializedCongressArchiveResult,
    materialize_congress_archive as materialize_congress_archive,
)
from src.runtime.congress_live_full import (
    run_live_congress_load_full as run_live_congress_load_full,
)
from src.runtime.congress_options import (
    CongressLoadOptions as CongressLoadOptions,
    current_congress_for_date as current_congress_for_date,
    resolve_congress_vote_coverage as resolve_congress_vote_coverage,
)
from src.runtime.context import RuntimeContext as RuntimeContext, open_connection as open_connection
from src.runtime.disclosures import (
    DisclosuresLoadRuntimeResult as DisclosuresLoadRuntimeResult,
    run_disclosures_load_runtime as run_disclosures_load_runtime,
)
from src.runtime.disclosures_artifacts import (
    run_disclosure_artifact_ingest as run_disclosure_artifact_ingest,
)
from src.runtime.disclosures_bundle import (
    DisclosuresBundle as DisclosuresBundle,
    load_disclosures_bundle as load_disclosures_bundle,
)
from src.runtime.disclosures_bundle_materialize import (
    MaterializedDisclosuresBundleResult as MaterializedDisclosuresBundleResult,
    materialize_disclosures_bundle as materialize_disclosures_bundle,
)
from src.runtime.disclosures_bundle_process import (
    DisclosuresBundleProcessResult as DisclosuresBundleProcessResult,
    run_disclosures_bundle_process as run_disclosures_bundle_process,
)
from src.runtime.disclosures_bundle_validate import (
    validate_disclosures_bundle as validate_disclosures_bundle,
)
from src.runtime.disclosures_load_from_parse import (
    run_disclosures_parse_load_runtime as run_disclosures_parse_load_runtime,
)
from src.runtime.disclosures_parse import (
    run_disclosure_parse_runtime as run_disclosure_parse_runtime,
)
from src.runtime.fec import (
    FecBulkFilePaths as FecBulkFilePaths,
    FecLocalLoadResult as FecLocalLoadResult,
    run_fec_local_load_runtime as run_fec_local_load_runtime,
)
from src.runtime.fec_bulk_materialize import (
    materialize_fec_bulk_files as materialize_fec_bulk_files,
)
from src.runtime.history_backfill import (
    LocalHistoryBackfillResult as LocalHistoryBackfillResult,
    build_history_backfill_report as build_history_backfill_report,
    check_history_backfill_inputs as check_history_backfill_inputs,
    plan_congress_history_backfill as plan_congress_history_backfill,
    run_local_history_backfill as run_local_history_backfill,
)
from src.runtime.history_verify import (
    verify_history_aggregate_local as _verify_local_history_aggregate,
)
from src.runtime.history_verify_types import HistoryVerifyResult as HistoryVerifyResult
from src.runtime.json_artifacts import write_json_artifact as _atomic_write_json_artifact
from src.runtime.member_fec_crosswalk import (
    MemberFecCrosswalkLoadResult as MemberFecCrosswalkLoadResult,
    load_member_fec_crosswalk_runtime as load_member_fec_crosswalk_runtime,
)
from src.runtime.member_fec_crosswalk_materialize import (
    materialize_member_fec_crosswalk as materialize_member_fec_crosswalk,
)
from src.runtime.oracle_contracts import (
    CongressOracleOptions as CongressOracleOptions,
    LocalOracleOptions as LocalOracleOptions,
    LocalOracleRunResult as LocalOracleRunResult,
)
from src.runtime.oracle_local import run_oracle_local as run_oracle_local
from src.runtime.output import (
    summarize_disclosure_artifact_ingest_result as summarize_disclosure_artifact_ingest_result,
    summarize_disclosures_bundle_process_result as summarize_disclosures_bundle_process_result,
    summarize_fec_load_result as summarize_fec_load_result,
    summarize_history_verify_result as summarize_history_verify_result,
    summarize_load_result as summarize_load_result,
    summarize_local_history_backfill_result as summarize_local_history_backfill_result,
    summarize_local_oracle_run_result as summarize_local_oracle_run_result,
    summarize_member_fec_crosswalk_load_result as summarize_member_fec_crosswalk_load_result,
    summarize_parse_disclosures_result as summarize_parse_disclosures_result,
    summarize_process_disclosures_result as summarize_process_disclosures_result,
    summarize_publish_result as summarize_publish_result,
    summarize_publish_roundtrip_result as summarize_publish_roundtrip_result,
    summarize_publish_verify_result as summarize_publish_verify_result,
    summarize_recompute_result as summarize_recompute_result,
)
from src.runtime.paths import local_artifact_root as local_artifact_root
from src.runtime.prediction_backtest import (
    handle_prediction_backtest_command as handle_prediction_backtest_command,
    prediction_backtest_source_state as _prediction_backtest_source_state_impl,
    run_prediction_backtest_command as _run_prediction_backtest_command,
    verify_prediction_backtest_command as verify_prediction_backtest_command,
)
from src.runtime.prediction_input_inventory import (
    handle_prediction_input_inventory_command as handle_prediction_input_inventory_command,
    prediction_input_inventory_source_state as _prediction_input_inventory_source_state_impl,
    run_prediction_input_inventory_command as _run_prediction_input_inventory_command,
    verify_prediction_input_inventory_command as verify_prediction_input_inventory_command,
)
from src.runtime.prediction_operator_resume_run import (
    verify_prediction_operator_resume_run as verify_prediction_operator_resume_run,
)
from src.runtime.prediction_source_url_audit import (
    run_prediction_source_url_audit_command as run_prediction_source_url_audit_command,
    verify_prediction_source_url_audit_command as verify_prediction_source_url_audit_command,
)
from src.runtime.public_statement_rows_materialize import (
    materialize_public_statement_rows as materialize_public_statement_rows,
)
from src.runtime.public_statement_rss_materialize import (
    materialize_public_statement_rss as materialize_public_statement_rss,
)
from src.runtime.publish import (
    PublishRuntimeResult as PublishRuntimeResult,
    run_publish_runtime as run_publish_runtime,
)
from src.runtime.publish_roundtrip import verify_roundtrip as _verify_roundtrip
from src.runtime.publish_roundtrip_types import PublishRoundtripResult as PublishRoundtripResult
from src.runtime.publish_verify import verify_local_publish as _verify_local_publish
from src.runtime.publish_verify_types import PublishVerifyResult as PublishVerifyResult
from src.runtime.recompute import (
    RuntimeRecomputeResult as RuntimeRecomputeResult,
    run_recompute_runtime as run_recompute_runtime,
)
from src.runtime.status_command import get_runtime_status as get_runtime_status
from src.runtime.zip_bundle import load_zip_bundle as load_zip_bundle
from types import SimpleNamespace as SimpleNamespace
from typing import Any as Any, cast as cast
from uuid import uuid4 as uuid4

from src.runtime.commands._shared import (
    _BENCHMARK_INVENTORY_FEATURE_SOURCE_COVERAGE_COUNT_KEYS as _BENCHMARK_INVENTORY_FEATURE_SOURCE_COVERAGE_COUNT_KEYS,
    _BENCHMARK_INVENTORY_FEATURE_SOURCE_COVERAGE_RATE_KEYS as _BENCHMARK_INVENTORY_FEATURE_SOURCE_COVERAGE_RATE_KEYS,
    _BENCHMARK_INVENTORY_SOURCE_COVERAGE_COUNT_KEYS as _BENCHMARK_INVENTORY_SOURCE_COVERAGE_COUNT_KEYS,
    _BENCHMARK_INVENTORY_SOURCE_COVERAGE_RATE_KEYS as _BENCHMARK_INVENTORY_SOURCE_COVERAGE_RATE_KEYS,
    _BENCHMARK_SOURCE_URL_AUDIT_COUNT_KEYS as _BENCHMARK_SOURCE_URL_AUDIT_COUNT_KEYS,
    _BENCHMARK_SOURCE_URL_AUDIT_INT_LIST_KEYS as _BENCHMARK_SOURCE_URL_AUDIT_INT_LIST_KEYS,
    _BENCHMARK_SOURCE_URL_AUDIT_STRING_LIST_KEYS as _BENCHMARK_SOURCE_URL_AUDIT_STRING_LIST_KEYS,
    _DEFAULT_RUNTIME_ENV_REQUIREMENTS as _DEFAULT_RUNTIME_ENV_REQUIREMENTS,
    _OPERATOR_EVAL_WINDOW_RUN_GATE_SOURCE_KEYS as _OPERATOR_EVAL_WINDOW_RUN_GATE_SOURCE_KEYS,
    _OPERATOR_EVAL_WINDOW_RUN_GATE_SOURCE_STATE_KEYS as _OPERATOR_EVAL_WINDOW_RUN_GATE_SOURCE_STATE_KEYS,
    _PREDICTION_OPERATOR_RESUME_PLAN_SAMPLE_STRING_KEYS as _PREDICTION_OPERATOR_RESUME_PLAN_SAMPLE_STRING_KEYS,
    _artifact_reference as _artifact_reference,
    _artifact_root_or_default as _artifact_root_or_default,
    _attach_optional_verification_output as _attach_optional_verification_output,
    _command_issue_result as _command_issue_result,
    _congress_archive_manifest_metadata as _congress_archive_manifest_metadata,
    _count_json_items as _count_json_items,
    _emit_verification_summary as _emit_verification_summary,
    _is_non_negative_plain_int as _is_non_negative_plain_int,
    _is_optional_non_negative_plain_int as _is_optional_non_negative_plain_int,
    _is_plain_int as _is_plain_int,
    _is_sha256_hex as _is_sha256_hex,
    _load_json_object_or_none as _load_json_object_or_none,
    _materialize_summary_file_hashes as _materialize_summary_file_hashes,
    _materialize_summary_run_metadata as _materialize_summary_run_metadata,
    _materialize_summary_source_urls as _materialize_summary_source_urls,
    _non_empty_line_count as _non_empty_line_count,
    _optional_file_sha256 as _optional_file_sha256,
    _optional_limit_issue as _optional_limit_issue,
    _plain_int_or_zero as _plain_int_or_zero,
    _positive_finite_timeout as _positive_finite_timeout,
    _positive_int_arg_issues as _positive_int_arg_issues,
    _positive_int_sequence_issues as _positive_int_sequence_issues,
    _prediction_operator_resume_plan_sorted_string_list as _prediction_operator_resume_plan_sorted_string_list,
    _required_string_list as _required_string_list,
    _sha256_file_path as _sha256_file_path,
    _single_value_or_none as _single_value_or_none,
    _sorted_string_list_or_empty as _sorted_string_list_or_empty,
    _string_list as _string_list,
    _write_bytes_artifact as _write_bytes_artifact,
    _write_json_artifact as _write_json_artifact,
)
from src.runtime.commands.statements import (
    _coerce_statement_row as _coerce_statement_row,
    _duplicate_statement_source_ids as _duplicate_statement_source_ids,
    _handle_materialize_public_statement_rows as _handle_materialize_public_statement_rows,
    _handle_materialize_public_statement_rss as _handle_materialize_public_statement_rss,
    _handle_verify_public_statement_rows as _handle_verify_public_statement_rows,
    _load_statement_rows as _load_statement_rows,
    _load_statement_rows_csv as _load_statement_rows_csv,
    _load_statement_rows_json as _load_statement_rows_json,
    _load_statement_rows_jsonl as _load_statement_rows_jsonl,
    _statement_rows_date_range as _statement_rows_date_range,
    _statement_rows_source_metadata as _statement_rows_source_metadata,
    _statement_source_id as _statement_source_id,
    _validate_statement_row as _validate_statement_row,
)
from src.runtime.commands.fec import (
    _handle_load_fec_local as _handle_load_fec_local,
    _handle_load_member_fec_crosswalk_local as _handle_load_member_fec_crosswalk_local,
    _handle_materialize_fec_bulk_files as _handle_materialize_fec_bulk_files,
    _handle_materialize_member_fec_crosswalk as _handle_materialize_member_fec_crosswalk,
    _handle_verify_fec_inputs as _handle_verify_fec_inputs,
    _has_strict_fec_inputs_verify_command as _has_strict_fec_inputs_verify_command,
    _member_fec_crosswalk_row_count as _member_fec_crosswalk_row_count,
    load_fec_local as load_fec_local,
    load_member_fec_crosswalk_local as load_member_fec_crosswalk_local,
)
from src.runtime.commands.disclosures import (
    _disclosure_summary as _disclosure_summary,
    _handle_load_disclosures as _handle_load_disclosures,
    _handle_materialize_disclosures_bundle as _handle_materialize_disclosures_bundle,
    _handle_parse_disclosures as _handle_parse_disclosures,
    _handle_process_disclosures as _handle_process_disclosures,
    _handle_process_disclosures_local as _handle_process_disclosures_local,
    _load_house_disclosures as _load_house_disclosures,
    _load_senate_disclosures as _load_senate_disclosures,
    _materialized_disclosures_bundle_summary as _materialized_disclosures_bundle_summary,
    _summarize_existing_disclosures_bundle as _summarize_existing_disclosures_bundle,
    load_disclosures as load_disclosures,
    process_disclosures_local as process_disclosures_local,
)
from src.runtime.commands.history import (
    _congress_archive_source_state as _congress_archive_source_state,
    _handle_aggregate_history as _handle_aggregate_history,
    _handle_check_history_backfill_inputs as _handle_check_history_backfill_inputs,
    _handle_materialize_congress_archive as _handle_materialize_congress_archive,
    _handle_materialize_history_backfill_inputs as _handle_materialize_history_backfill_inputs,
    _handle_plan_history_backfill as _handle_plan_history_backfill,
    _handle_run_history_backfill_local as _handle_run_history_backfill_local,
    _handle_run_history_launch_local as _handle_run_history_launch_local,
    _handle_verify_history_aggregate as _handle_verify_history_aggregate,
    _handle_write_congress_archive_manifest as _handle_write_congress_archive_manifest,
    _materialize_history_backfill_inputs as _materialize_history_backfill_inputs,
    _materialized_congress_archive_summary as _materialized_congress_archive_summary,
    _reusable_congress_archive_path as _reusable_congress_archive_path,
    _should_reuse_existing_congress_archive as _should_reuse_existing_congress_archive,
    _summarize_existing_congress_archive as _summarize_existing_congress_archive,
    _validate_congress_archive_manifest_metadata as _validate_congress_archive_manifest_metadata,
    run_history_backfill_local_command as run_history_backfill_local_command,
    verify_history_aggregate_local as verify_history_aggregate_local,
)
from src.runtime.commands.runtime_env import (
    _handle_runtime_env_preflight as _handle_runtime_env_preflight,
    _handle_verify_runtime_env_preflight as _handle_verify_runtime_env_preflight,
    _read_dotenv_key_presence as _read_dotenv_key_presence,
    _runtime_env_check as _runtime_env_check,
    _runtime_env_create_dotenv_from_template_action as _runtime_env_create_dotenv_from_template_action,
    _runtime_env_next_actions_by_env_summary as _runtime_env_next_actions_by_env_summary,
    _runtime_env_preflight_count_issues as _runtime_env_preflight_count_issues,
    _runtime_env_preflight_next_actions_by_env as _runtime_env_preflight_next_actions_by_env,
    _runtime_env_preflight_secret_literal_failures as _runtime_env_preflight_secret_literal_failures,
    _runtime_env_preflight_verify_run_metadata as _runtime_env_preflight_verify_run_metadata,
    _write_runtime_env_template as _write_runtime_env_template,
)
from src.runtime.commands.core import (
    _BENCHMARK_BACKTEST_SOURCE_COVERAGE_COUNT_KEYS as _BENCHMARK_BACKTEST_SOURCE_COVERAGE_COUNT_KEYS,
    _BENCHMARK_BACKTEST_SOURCE_COVERAGE_KEYS as _BENCHMARK_BACKTEST_SOURCE_COVERAGE_KEYS,
    _BENCHMARK_BACKTEST_SOURCE_COVERAGE_RATE_KEYS as _BENCHMARK_BACKTEST_SOURCE_COVERAGE_RATE_KEYS,
    _BENCHMARK_EVAL_CUTOFF_AUDIT_COUNT_KEYS as _BENCHMARK_EVAL_CUTOFF_AUDIT_COUNT_KEYS,
    _BENCHMARK_EVAL_CUTOFF_AUDIT_SOURCE_STATE_KEYS as _BENCHMARK_EVAL_CUTOFF_AUDIT_SOURCE_STATE_KEYS,
    _BENCHMARK_INVENTORY_FEATURE_SOURCE_COVERAGE_KEYS as _BENCHMARK_INVENTORY_FEATURE_SOURCE_COVERAGE_KEYS,
    _BENCHMARK_INVENTORY_SOURCE_COVERAGE_KEYS as _BENCHMARK_INVENTORY_SOURCE_COVERAGE_KEYS,
    _JURISDICTION_SEMANTIC_ADAPTER_SOURCE_REQUIREMENT as _JURISDICTION_SEMANTIC_ADAPTER_SOURCE_REQUIREMENT,
    _OFFLINE_READINESS_BENCHMARK_EVAL_CUTOFF_AUDIT_KEYS as _OFFLINE_READINESS_BENCHMARK_EVAL_CUTOFF_AUDIT_KEYS,
    _PREDICTION_BACKFILL_DATA_ACTION_ORDER as _PREDICTION_BACKFILL_DATA_ACTION_ORDER,
    _PREDICTION_BACKFILL_REFRESH_ACTION_ORDER as _PREDICTION_BACKFILL_REFRESH_ACTION_ORDER,
    _PREDICTION_BACKFILL_SUGGESTED_COMMAND_PREFIXES as _PREDICTION_BACKFILL_SUGGESTED_COMMAND_PREFIXES,
    _PREDICTION_BACKFILL_SUPPORTED_COMMAND_ACTIONS as _PREDICTION_BACKFILL_SUPPORTED_COMMAND_ACTIONS,
    _PREDICTION_EVAL_CUTOFF_AUDIT_KEYS as _PREDICTION_EVAL_CUTOFF_AUDIT_KEYS,
    _PREDICTION_EVAL_INT_THRESHOLD_ARGS as _PREDICTION_EVAL_INT_THRESHOLD_ARGS,
    _PREDICTION_EVAL_MANIFEST_BOOL_THRESHOLDS as _PREDICTION_EVAL_MANIFEST_BOOL_THRESHOLDS,
    _PREDICTION_EVAL_MANIFEST_COVERAGE_THRESHOLDS as _PREDICTION_EVAL_MANIFEST_COVERAGE_THRESHOLDS,
    _PREDICTION_EVAL_MANIFEST_FAILURE_ANALYSIS_KEYS as _PREDICTION_EVAL_MANIFEST_FAILURE_ANALYSIS_KEYS,
    _PREDICTION_EVAL_MANIFEST_INT_THRESHOLDS as _PREDICTION_EVAL_MANIFEST_INT_THRESHOLDS,
    _PREDICTION_EVAL_MANIFEST_RATE_THRESHOLDS as _PREDICTION_EVAL_MANIFEST_RATE_THRESHOLDS,
    _PREDICTION_EVAL_MANIFEST_REQUIRED_BOOL_THRESHOLDS as _PREDICTION_EVAL_MANIFEST_REQUIRED_BOOL_THRESHOLDS,
    _PREDICTION_EVAL_MANIFEST_THRESHOLD_KEYS as _PREDICTION_EVAL_MANIFEST_THRESHOLD_KEYS,
    _PREDICTION_EVAL_RATE_THRESHOLD_ARGS as _PREDICTION_EVAL_RATE_THRESHOLD_ARGS,
    _PREDICTION_OFFLINE_READINESS_SOURCE_STATE_STRING_LIST_KEYS as _PREDICTION_OFFLINE_READINESS_SOURCE_STATE_STRING_LIST_KEYS,
    _SOURCE_FAMILY_ID_RE as _SOURCE_FAMILY_ID_RE,
    _append_issue_once as _append_issue_once,
    _append_unique_objects as _append_unique_objects,
    _append_unique_strings as _append_unique_strings,
    _compact_status as _compact_status,
    _congresses_from_bill_keys as _congresses_from_bill_keys,
    _current_congress as _current_congress,
    _date_from_iso_string as _date_from_iso_string,
    _file_sha256 as _file_sha256,
    _float_option_value_from_command as _float_option_value_from_command,
    _handle_bootstrap_db as _handle_bootstrap_db,
    _handle_load_congress as _handle_load_congress,
    _handle_load_congress_local as _handle_load_congress_local,
    _handle_publish as _handle_publish,
    _handle_recompute as _handle_recompute,
    _handle_run_oracle_local as _handle_run_oracle_local,
    _handle_status as _handle_status,
    _handle_verify_publish as _handle_verify_publish,
    _handle_verify_publish_roundtrip as _handle_verify_publish_roundtrip,
    _has_strict_source_url_audit_verify_command as _has_strict_source_url_audit_verify_command,
    _int_option_value_from_command as _int_option_value_from_command,
    _is_official_plan_source_anchor as _is_official_plan_source_anchor,
    _is_present_invalid_iso_date as _is_present_invalid_iso_date,
    _json_scalar_type_mismatch as _json_scalar_type_mismatch,
    _manifest_failure_analysis_int as _manifest_failure_analysis_int,
    _mapping_mismatch_key_issues as _mapping_mismatch_key_issues,
    _merge_int_count_dicts as _merge_int_count_dicts,
    _missing_required_source_family_ids as _missing_required_source_family_ids,
    _non_empty_string_list as _non_empty_string_list,
    _normalized_source_family_ids as _normalized_source_family_ids,
    _numeric_or_none_matches as _numeric_or_none_matches,
    _object_list as _object_list,
    _ontology_signal_requires_source_anchor as _ontology_signal_requires_source_anchor,
    _option_value_from_command as _option_value_from_command,
    _option_values_from_command as _option_values_from_command,
    _oracle_summary_ok as _oracle_summary_ok,
    _path_from_payload as _path_from_payload,
    _publish_summary_ok as _publish_summary_ok,
    _publish_target_or_default as _publish_target_or_default,
    _rate_meets_minimum as _rate_meets_minimum,
    _required_model_names as _required_model_names,
    _required_source_family_ids as _required_source_family_ids,
    _run_metadata_source_state as _run_metadata_source_state,
    _snapshot_date_or_today as _snapshot_date_or_today,
    _source_family_id_list as _source_family_id_list,
    _stable_json_key as _stable_json_key,
    _strict_int_count_dict as _strict_int_count_dict,
    _strict_non_negative_int_list as _strict_non_negative_int_list,
    _strict_nonblank_string as _strict_nonblank_string,
    _strict_object_list as _strict_object_list,
    _strict_string_list as _strict_string_list,
    _strict_string_values as _strict_string_values,
    _string_list_from_plan as _string_list_from_plan,
    _string_list_has_duplicates as _string_list_has_duplicates,
    _string_list_has_empty as _string_list_has_empty,
    _string_list_has_untrimmed as _string_list_has_untrimmed,
    _string_values as _string_values,
    _top_learned_signal_coefficients as _top_learned_signal_coefficients,
    _write_text_artifact as _write_text_artifact,
    load_congress as load_congress,
    load_congress_local as load_congress_local,
    publish_snapshot as publish_snapshot,
    recompute_snapshot as recompute_snapshot,
    run_oracle_local_command as run_oracle_local_command,
    verify_publish_local as verify_publish_local,
    verify_publish_roundtrip_local as verify_publish_roundtrip_local,
)
from src.runtime.commands.bill_semantics import (
    _NoopBillSemanticExtractor as _NoopBillSemanticExtractor,
    _attach_materialize_bill_semantics_summary_output as _attach_materialize_bill_semantics_summary_output,
    _bill_semantic_cutoff_ineligible_keys_from_report as _bill_semantic_cutoff_ineligible_keys_from_report,
    _bill_semantic_materialization_plan as _bill_semantic_materialization_plan,
    _bill_semantic_missing_keys_from_report as _bill_semantic_missing_keys_from_report,
    _bill_semantic_plan_report_metadata as _bill_semantic_plan_report_metadata,
    _bill_semantic_report_keys_from_coverage as _bill_semantic_report_keys_from_coverage,
    _bill_semantics_plan_invalid_source_state_count_keys as _bill_semantics_plan_invalid_source_state_count_keys,
    _bill_semantics_plan_source_state_count_issues as _bill_semantics_plan_source_state_count_issues,
    _bill_semantics_plan_verify_run_metadata as _bill_semantics_plan_verify_run_metadata,
    _bill_semantics_plan_verify_source_state as _bill_semantics_plan_verify_source_state,
    _bill_semantics_unavailable_source_state as _bill_semantics_unavailable_source_state,
    _bill_semantics_unofficial_source_anchor_count as _bill_semantics_unofficial_source_anchor_count,
    _bill_semantics_verify_run_metadata as _bill_semantics_verify_run_metadata,
    _bill_semantics_verify_source_state as _bill_semantics_verify_source_state,
    _handle_materialize_bill_semantics as _handle_materialize_bill_semantics,
    _handle_verify_bill_semantics as _handle_verify_bill_semantics,
    _handle_verify_bill_semantics_plan as _handle_verify_bill_semantics_plan,
    _has_strict_bill_semantics_verify_command as _has_strict_bill_semantics_verify_command,
    _manifest_has_bill_semantics_cache as _manifest_has_bill_semantics_cache,
    _materialize_bill_semantic_row_key as _materialize_bill_semantic_row_key,
    _materialize_bill_semantic_target_keys as _materialize_bill_semantic_target_keys,
    _materialize_bill_semantic_targeting_requested as _materialize_bill_semantic_targeting_requested,
    _materialize_bill_semantics_source_report_metadata as _materialize_bill_semantics_source_report_metadata,
    _materialize_bill_semantics_source_state as _materialize_bill_semantics_source_state,
    _missing_bill_semantics_cache_result as _missing_bill_semantics_cache_result,
    _unsupported_bill_semantic_target_keys as _unsupported_bill_semantic_target_keys,
    _validate_bill_semantics_plan_inputs as _validate_bill_semantics_plan_inputs,
    _validate_bill_semantics_plan_matched_bills as _validate_bill_semantics_plan_matched_bills,
    _validate_bill_semantics_plan_run_metadata as _validate_bill_semantics_plan_run_metadata,
)
from src.runtime.commands.prediction_misc import (
    _handle_prediction_backtest as _handle_prediction_backtest,
    _handle_prediction_input_inventory as _handle_prediction_input_inventory,
    _handle_prediction_source_url_audit as _handle_prediction_source_url_audit,
    _handle_verify_prediction_backtest as _handle_verify_prediction_backtest,
    _handle_verify_prediction_input_inventory as _handle_verify_prediction_input_inventory,
    _handle_verify_prediction_source_url_audit as _handle_verify_prediction_source_url_audit,
    _has_prediction_backtest_archive_manifest_command as _has_prediction_backtest_archive_manifest_command,
    _has_prediction_backtest_archive_verify_command as _has_prediction_backtest_archive_verify_command,
    _has_prediction_input_inventory_archive_manifest_command as _has_prediction_input_inventory_archive_manifest_command,
    _has_prediction_input_inventory_archive_verify_command as _has_prediction_input_inventory_archive_verify_command,
    _has_strict_prediction_backtest_verify_command as _has_strict_prediction_backtest_verify_command,
    _has_strict_prediction_input_inventory_verify_command as _has_strict_prediction_input_inventory_verify_command,
    _missing_prediction_source_url_audit_result as _missing_prediction_source_url_audit_result,
    _prediction_backtest_refresh_commands as _prediction_backtest_refresh_commands,
    _prediction_backtest_run_metadata as _prediction_backtest_run_metadata,
    _prediction_backtest_source_state as _prediction_backtest_source_state,
    _prediction_backtest_verify_run_metadata as _prediction_backtest_verify_run_metadata,
    _prediction_input_inventory_refresh_commands as _prediction_input_inventory_refresh_commands,
    _prediction_input_inventory_source_state as _prediction_input_inventory_source_state,
    _prediction_window_date_issues as _prediction_window_date_issues,
    run_prediction_backtest_command as run_prediction_backtest_command,
    run_prediction_input_inventory_command as run_prediction_input_inventory_command,
)
from src.runtime.commands.prediction_eval import (
    _feature_source_anchor_count as _feature_source_anchor_count,
    _feature_source_coverage_rate as _feature_source_coverage_rate,
    _feature_source_official_source_anchor_count as _feature_source_official_source_anchor_count,
    _feature_source_official_source_coverage_rate as _feature_source_official_source_coverage_rate,
    _feature_source_official_source_sourced_prediction_count as _feature_source_official_source_sourced_prediction_count,
    _feature_source_prediction_count as _feature_source_prediction_count,
    _feature_source_sourced_prediction_count as _feature_source_sourced_prediction_count,
    _feature_source_url_anchor_count as _feature_source_url_anchor_count,
    _feature_source_url_coverage_rate as _feature_source_url_coverage_rate,
    _feature_source_url_sourced_prediction_count as _feature_source_url_sourced_prediction_count,
    _handle_prediction_eval_report as _handle_prediction_eval_report,
    _handle_verify_prediction_eval_manifest as _handle_verify_prediction_eval_manifest,
    _has_prediction_eval_manifest_archive_verify_command as _has_prediction_eval_manifest_archive_verify_command,
    _has_prediction_eval_report_archive_manifest_command as _has_prediction_eval_report_archive_manifest_command,
    _has_strict_prediction_eval_manifest_verify_command as _has_strict_prediction_eval_manifest_verify_command,
    _load_prediction_eval_artifact_json as _load_prediction_eval_artifact_json,
    _load_prediction_eval_dataset_from_artifacts as _load_prediction_eval_dataset_from_artifacts,
    _load_prediction_eval_report_from_artifacts as _load_prediction_eval_report_from_artifacts,
    _prediction_cutoff_partition_values_valid as _prediction_cutoff_partition_values_valid,
    _prediction_eval_cutoff_audit_partition_issues as _prediction_eval_cutoff_audit_partition_issues,
    _prediction_eval_cutoff_audit_summary as _prediction_eval_cutoff_audit_summary,
    _prediction_eval_feature_source_state as _prediction_eval_feature_source_state,
    _prediction_eval_implemented_jurisdiction_count as _prediction_eval_implemented_jurisdiction_count,
    _prediction_eval_implemented_jurisdiction_ids as _prediction_eval_implemented_jurisdiction_ids,
    _prediction_eval_invalid_coverage_threshold_issues as _prediction_eval_invalid_coverage_threshold_issues,
    _prediction_eval_jurisdiction_count as _prediction_eval_jurisdiction_count,
    _prediction_eval_jurisdiction_ids as _prediction_eval_jurisdiction_ids,
    _prediction_eval_legislative_body_count as _prediction_eval_legislative_body_count,
    _prediction_eval_legislative_body_id as _prediction_eval_legislative_body_id,
    _prediction_eval_legislative_body_ids as _prediction_eval_legislative_body_ids,
    _prediction_eval_legislative_session_count as _prediction_eval_legislative_session_count,
    _prediction_eval_legislative_session_ids as _prediction_eval_legislative_session_ids,
    _prediction_eval_manifest as _prediction_eval_manifest,
    _prediction_eval_manifest_backfill_recommendation_shape_failures as _prediction_eval_manifest_backfill_recommendation_shape_failures,
    _prediction_eval_manifest_coverage_threshold_failures as _prediction_eval_manifest_coverage_threshold_failures,
    _prediction_eval_manifest_cutoff_ineligible_backfill_failures as _prediction_eval_manifest_cutoff_ineligible_backfill_failures,
    _prediction_eval_manifest_failure_analysis_failures as _prediction_eval_manifest_failure_analysis_failures,
    _prediction_eval_manifest_failure_group_sample_failures as _prediction_eval_manifest_failure_group_sample_failures,
    _prediction_eval_manifest_input_model_names_are_valid as _prediction_eval_manifest_input_model_names_are_valid,
    _prediction_eval_manifest_invalid_coverage_thresholds as _prediction_eval_manifest_invalid_coverage_thresholds,
    _prediction_eval_manifest_model_names as _prediction_eval_manifest_model_names,
    _prediction_eval_manifest_ontology_feature_signal_state as _prediction_eval_manifest_ontology_feature_signal_state,
    _prediction_eval_manifest_ready_quality_failures as _prediction_eval_manifest_ready_quality_failures,
    _prediction_eval_manifest_required_model_failures as _prediction_eval_manifest_required_model_failures,
    _prediction_eval_manifest_required_threshold_failures as _prediction_eval_manifest_required_threshold_failures,
    _prediction_eval_manifest_sample_case_shape_failures as _prediction_eval_manifest_sample_case_shape_failures,
    _prediction_eval_manifest_source_artifact_sha256 as _prediction_eval_manifest_source_artifact_sha256,
    _prediction_eval_manifest_unknown_availability_failures as _prediction_eval_manifest_unknown_availability_failures,
    _prediction_eval_manifest_verify_run_metadata as _prediction_eval_manifest_verify_run_metadata,
    _prediction_eval_manifest_verify_source_state as _prediction_eval_manifest_verify_source_state,
    _prediction_eval_optional_path_string_issue as _prediction_eval_optional_path_string_issue,
    _prediction_eval_optional_rate_valid as _prediction_eval_optional_rate_valid,
    _prediction_eval_optional_sha256_issue as _prediction_eval_optional_sha256_issue,
    _prediction_eval_portable_jurisdiction_count as _prediction_eval_portable_jurisdiction_count,
    _prediction_eval_portable_jurisdiction_ids as _prediction_eval_portable_jurisdiction_ids,
    _prediction_eval_quality_gate_failures as _prediction_eval_quality_gate_failures,
    _prediction_eval_report_refresh_commands as _prediction_eval_report_refresh_commands,
    _prediction_eval_run_metadata_matches_expected as _prediction_eval_run_metadata_matches_expected,
    _prediction_eval_source_family_id as _prediction_eval_source_family_id,
    _prediction_eval_source_family_ids as _prediction_eval_source_family_ids,
    _prediction_eval_source_state as _prediction_eval_source_state,
    _prediction_eval_source_state_count_key as _prediction_eval_source_state_count_key,
    _prediction_eval_source_state_rate_valid as _prediction_eval_source_state_rate_valid,
    _prediction_eval_source_state_scope_invariant_keys as _prediction_eval_source_state_scope_invariant_keys,
    _prediction_eval_source_state_scoped_id_keys as _prediction_eval_source_state_scoped_id_keys,
    _prediction_eval_split_missing_source_anchor_signal_names as _prediction_eval_split_missing_source_anchor_signal_names,
    _prediction_eval_split_source_backed_signal_names as _prediction_eval_split_source_backed_signal_names,
    _prediction_eval_thresholds as _prediction_eval_thresholds,
    _prediction_window_run_metadata as _prediction_window_run_metadata,
    _validate_prediction_eval_artifact_run_metadata as _validate_prediction_eval_artifact_run_metadata,
    _validate_prediction_eval_artifact_schema as _validate_prediction_eval_artifact_schema,
    _validate_prediction_eval_manifest_coverage as _validate_prediction_eval_manifest_coverage,
    _validate_prediction_eval_manifest_failure_analysis as _validate_prediction_eval_manifest_failure_analysis,
    _validate_prediction_eval_manifest_inputs_shape as _validate_prediction_eval_manifest_inputs_shape,
    _validate_prediction_eval_manifest_learned_model as _validate_prediction_eval_manifest_learned_model,
    _validate_prediction_eval_manifest_payload_consistency as _validate_prediction_eval_manifest_payload_consistency,
    _validate_prediction_eval_manifest_quality as _validate_prediction_eval_manifest_quality,
    _validate_prediction_eval_manifest_run_metadata as _validate_prediction_eval_manifest_run_metadata,
    _validate_prediction_eval_manifest_source_state as _validate_prediction_eval_manifest_source_state,
    _validate_prediction_eval_manifest_windows as _validate_prediction_eval_manifest_windows,
    _validate_prediction_eval_source_state_shape as _validate_prediction_eval_source_state_shape,
    _validated_prediction_eval_manifest_thresholds as _validated_prediction_eval_manifest_thresholds,
    run_prediction_eval_report_command as run_prediction_eval_report_command,
)
from src.runtime.commands.prediction_eval_windows import (
    _handle_prediction_eval_window_plan as _handle_prediction_eval_window_plan,
    _handle_prediction_eval_window_summary as _handle_prediction_eval_window_summary,
    _handle_verify_prediction_eval_window_plan as _handle_verify_prediction_eval_window_plan,
    _handle_verify_prediction_eval_window_run as _handle_verify_prediction_eval_window_run,
    _handle_verify_prediction_eval_window_summary as _handle_verify_prediction_eval_window_summary,
    _missing_prediction_eval_window_run_verify_result as _missing_prediction_eval_window_run_verify_result,
    _prediction_eval_window_expected_command_fragments as _prediction_eval_window_expected_command_fragments,
    _prediction_eval_window_plan_command_issues as _prediction_eval_window_plan_command_issues,
    _prediction_eval_window_plan_expected_report_paths as _prediction_eval_window_plan_expected_report_paths,
    _prediction_eval_window_plan_run_metadata_value as _prediction_eval_window_plan_run_metadata_value,
    _prediction_eval_window_plan_source_state as _prediction_eval_window_plan_source_state,
    _prediction_eval_window_plan_verify_run_metadata as _prediction_eval_window_plan_verify_run_metadata,
    _prediction_eval_window_run_artifact_issues as _prediction_eval_window_run_artifact_issues,
    _prediction_eval_window_run_congress_archive_manifest_issues as _prediction_eval_window_run_congress_archive_manifest_issues,
    _prediction_eval_window_run_expected_summary_verify as _prediction_eval_window_run_expected_summary_verify,
    _prediction_eval_window_run_expected_summary_windows as _prediction_eval_window_run_expected_summary_windows,
    _prediction_eval_window_run_expected_verification_flags as _prediction_eval_window_run_expected_verification_flags,
    _prediction_eval_window_run_expected_window_verifiers as _prediction_eval_window_run_expected_window_verifiers,
    _prediction_eval_window_run_plan_congress_archive_manifest as _prediction_eval_window_run_plan_congress_archive_manifest,
    _prediction_eval_window_run_source_congress_archive_manifest as _prediction_eval_window_run_source_congress_archive_manifest,
    _prediction_eval_window_run_strict_flag_state as _prediction_eval_window_run_strict_flag_state,
    _prediction_eval_window_run_summary_plan_metadata_issues as _prediction_eval_window_run_summary_plan_metadata_issues,
    _prediction_eval_window_run_summary_window_projection as _prediction_eval_window_run_summary_window_projection,
    _prediction_eval_window_run_verification_flags_issues as _prediction_eval_window_run_verification_flags_issues,
    _prediction_eval_window_run_verified_source_artifact_path as _prediction_eval_window_run_verified_source_artifact_path,
    _prediction_eval_window_run_verifier_issue as _prediction_eval_window_run_verifier_issue,
    _prediction_eval_window_run_verifier_result as _prediction_eval_window_run_verifier_result,
    _prediction_eval_window_run_verifier_results as _prediction_eval_window_run_verifier_results,
    _prediction_eval_window_run_verify_run_metadata as _prediction_eval_window_run_verify_run_metadata,
    _prediction_eval_window_run_verify_source_state as _prediction_eval_window_run_verify_source_state,
    _prediction_eval_window_summary_models as _prediction_eval_window_summary_models,
    _prediction_eval_window_summary_run_metadata as _prediction_eval_window_summary_run_metadata,
    _prediction_eval_window_summary_source_state_window as _prediction_eval_window_summary_source_state_window,
    _prediction_eval_window_summary_verify_run_metadata as _prediction_eval_window_summary_verify_run_metadata,
    _prediction_eval_window_summary_verify_source_state as _prediction_eval_window_summary_verify_source_state,
    _prediction_eval_window_summary_window as _prediction_eval_window_summary_window,
    _validate_prediction_eval_window_plan_run_metadata as _validate_prediction_eval_window_plan_run_metadata,
    _validate_prediction_eval_window_summary_counts as _validate_prediction_eval_window_summary_counts,
    _validate_prediction_eval_window_summary_current_hashes as _validate_prediction_eval_window_summary_current_hashes,
    _validate_prediction_eval_window_summary_model as _validate_prediction_eval_window_summary_model,
    _validate_prediction_eval_window_summary_non_overlapping_windows as _validate_prediction_eval_window_summary_non_overlapping_windows,
    _validate_prediction_eval_window_summary_plan_match as _validate_prediction_eval_window_summary_plan_match,
    _validate_prediction_eval_window_summary_report_metadata as _validate_prediction_eval_window_summary_report_metadata,
    _validate_prediction_eval_window_summary_run_metadata as _validate_prediction_eval_window_summary_run_metadata,
    _validate_prediction_eval_window_summary_window_dates as _validate_prediction_eval_window_summary_window_dates,
    run_prediction_eval_window_plan_command as run_prediction_eval_window_plan_command,
)
from src.runtime.commands.prediction_benchmark import (
    _canonical_prediction_benchmark_backfill_recommendation as _canonical_prediction_benchmark_backfill_recommendation,
    _coalesce_prediction_benchmark_backfill_recommendations as _coalesce_prediction_benchmark_backfill_recommendations,
    _handle_verify_prediction_backfill_plan as _handle_verify_prediction_backfill_plan,
    _handle_verify_prediction_benchmark as _handle_verify_prediction_benchmark,
    _merge_prediction_benchmark_backfill_recommendation as _merge_prediction_benchmark_backfill_recommendation,
    _missing_prediction_backfill_runtime_requirements as _missing_prediction_backfill_runtime_requirements,
    _ordered_prediction_benchmark_backfill_steps as _ordered_prediction_benchmark_backfill_steps,
    _prediction_backfill_action_order as _prediction_backfill_action_order,
    _prediction_backfill_plan_benchmark_eval_cutoff_state_valid as _prediction_backfill_plan_benchmark_eval_cutoff_state_valid,
    _prediction_backfill_plan_benchmark_inventory_feature_source_state_valid as _prediction_backfill_plan_benchmark_inventory_feature_source_state_valid,
    _prediction_backfill_plan_benchmark_inventory_source_state_valid as _prediction_backfill_plan_benchmark_inventory_source_state_valid,
    _prediction_backfill_plan_benchmark_sample_state_valid as _prediction_backfill_plan_benchmark_sample_state_valid,
    _prediction_backfill_plan_benchmark_scope_state_valid as _prediction_backfill_plan_benchmark_scope_state_valid,
    _prediction_backfill_plan_benchmark_source_state_matches as _prediction_backfill_plan_benchmark_source_state_matches,
    _prediction_backfill_plan_benchmark_source_url_audit_state_valid as _prediction_backfill_plan_benchmark_source_url_audit_state_valid,
    _prediction_backfill_plan_cutoff_partition_valid as _prediction_backfill_plan_cutoff_partition_valid,
    _prediction_backfill_plan_missing_metadata_bill_keys as _prediction_backfill_plan_missing_metadata_bill_keys,
    _prediction_backfill_plan_non_negative_int_list as _prediction_backfill_plan_non_negative_int_list,
    _prediction_backfill_plan_sample_scoped_ids_valid as _prediction_backfill_plan_sample_scoped_ids_valid,
    _prediction_backfill_plan_sorted_string_list as _prediction_backfill_plan_sorted_string_list,
    _prediction_backfill_plan_string_list as _prediction_backfill_plan_string_list,
    _prediction_backfill_plan_verify_run_metadata as _prediction_backfill_plan_verify_run_metadata,
    _prediction_backfill_plan_verify_source_state as _prediction_backfill_plan_verify_source_state,
    _prediction_backfill_suggested_command_supported as _prediction_backfill_suggested_command_supported,
    _prediction_backfill_supported_command_step_count as _prediction_backfill_supported_command_step_count,
    _prediction_backfill_unsupported_semantic_bill_keys as _prediction_backfill_unsupported_semantic_bill_keys,
    _prediction_benchmark_backfill_blockers as _prediction_benchmark_backfill_blockers,
    _prediction_benchmark_backfill_commands as _prediction_benchmark_backfill_commands,
    _prediction_benchmark_backfill_plan as _prediction_benchmark_backfill_plan,
    _prediction_benchmark_backfill_plan_artifact as _prediction_benchmark_backfill_plan_artifact,
    _prediction_benchmark_backfill_plan_missing_runtime_requirements as _prediction_benchmark_backfill_plan_missing_runtime_requirements,
    _prediction_benchmark_backfill_recommendations as _prediction_benchmark_backfill_recommendations,
    _prediction_benchmark_backfill_runtime_requirements as _prediction_benchmark_backfill_runtime_requirements,
    _prediction_benchmark_backfill_source_requirements as _prediction_benchmark_backfill_source_requirements,
    _prediction_benchmark_backfill_step as _prediction_benchmark_backfill_step,
    _prediction_benchmark_backtest_backfill_recommendations as _prediction_benchmark_backtest_backfill_recommendations,
    _prediction_benchmark_backtest_source_coverage as _prediction_benchmark_backtest_source_coverage,
    _prediction_benchmark_bundle_consistency_issues as _prediction_benchmark_bundle_consistency_issues,
    _prediction_benchmark_component_scope_counts as _prediction_benchmark_component_scope_counts,
    _prediction_benchmark_congress_archive_manifest_consistency_issues as _prediction_benchmark_congress_archive_manifest_consistency_issues,
    _prediction_benchmark_congress_archive_manifest_reference as _prediction_benchmark_congress_archive_manifest_reference,
    _prediction_benchmark_eval_cutoff_audit as _prediction_benchmark_eval_cutoff_audit,
    _prediction_benchmark_eval_feature_cutoff as _prediction_benchmark_eval_feature_cutoff,
    _prediction_benchmark_eval_label_congresses as _prediction_benchmark_eval_label_congresses,
    _prediction_benchmark_eval_manifest_backfill_recommendations as _prediction_benchmark_eval_manifest_backfill_recommendations,
    _prediction_benchmark_eval_report_path as _prediction_benchmark_eval_report_path,
    _prediction_benchmark_eval_window_run_component_metadata as _prediction_benchmark_eval_window_run_component_metadata,
    _prediction_benchmark_eval_window_run_source_state_stale_fields as _prediction_benchmark_eval_window_run_source_state_stale_fields,
    _prediction_benchmark_eval_window_run_stale_fields as _prediction_benchmark_eval_window_run_stale_fields,
    _prediction_benchmark_eval_window_run_strict_source_state as _prediction_benchmark_eval_window_run_strict_source_state,
    _prediction_benchmark_eval_window_run_verify_result as _prediction_benchmark_eval_window_run_verify_result,
    _prediction_benchmark_inventory_backfill_recommendations as _prediction_benchmark_inventory_backfill_recommendations,
    _prediction_benchmark_inventory_source_gaps as _prediction_benchmark_inventory_source_gaps,
    _prediction_benchmark_run_metadata as _prediction_benchmark_run_metadata,
    _prediction_benchmark_source_state as _prediction_benchmark_source_state,
    _prediction_benchmark_source_url_audit_backfill_recommendations as _prediction_benchmark_source_url_audit_backfill_recommendations,
    _prediction_benchmark_source_url_audit_gaps as _prediction_benchmark_source_url_audit_gaps,
    _prediction_benchmark_verification_flags as _prediction_benchmark_verification_flags,
    _validate_prediction_backfill_plan_run_metadata as _validate_prediction_backfill_plan_run_metadata,
    _validate_prediction_backfill_plan_source_state as _validate_prediction_backfill_plan_source_state,
    _validate_prediction_backfill_sample_cases as _validate_prediction_backfill_sample_cases,
    _validate_prediction_backfill_source_eval_report as _validate_prediction_backfill_source_eval_report,
    _validate_prediction_benchmark_run_metadata_artifact_sha256 as _validate_prediction_benchmark_run_metadata_artifact_sha256,
)
from src.runtime.commands.prediction_readiness import (
    _attach_prediction_readiness_provenance as _attach_prediction_readiness_provenance,
    _handle_prediction_offline_readiness_summary as _handle_prediction_offline_readiness_summary,
    _handle_verify_prediction_offline_readiness_summary as _handle_verify_prediction_offline_readiness_summary,
    _handle_verify_prediction_resume_script as _handle_verify_prediction_resume_script,
    _load_prediction_readiness_artifact as _load_prediction_readiness_artifact,
    _prediction_offline_readiness_benchmark_scope_shape_issues as _prediction_offline_readiness_benchmark_scope_shape_issues,
    _prediction_offline_readiness_benchmark_scoped_id_issues as _prediction_offline_readiness_benchmark_scoped_id_issues,
    _prediction_offline_readiness_congress_requirement_issues as _prediction_offline_readiness_congress_requirement_issues,
    _prediction_offline_readiness_count_issues as _prediction_offline_readiness_count_issues,
    _prediction_offline_readiness_eval_window_run_archive_manifest_issues as _prediction_offline_readiness_eval_window_run_archive_manifest_issues,
    _prediction_offline_readiness_eval_window_run_gate_issues as _prediction_offline_readiness_eval_window_run_gate_issues,
    _prediction_offline_readiness_expected_source_state as _prediction_offline_readiness_expected_source_state,
    _prediction_offline_readiness_invalid_source_state_count_keys as _prediction_offline_readiness_invalid_source_state_count_keys,
    _prediction_offline_readiness_resume_script_state as _prediction_offline_readiness_resume_script_state,
    _prediction_offline_readiness_run_metadata as _prediction_offline_readiness_run_metadata,
    _prediction_offline_readiness_sample_scoped_id_issues as _prediction_offline_readiness_sample_scoped_id_issues,
    _prediction_offline_readiness_secret_literal_failures as _prediction_offline_readiness_secret_literal_failures,
    _prediction_offline_readiness_source_artifact_sha256 as _prediction_offline_readiness_source_artifact_sha256,
    _prediction_offline_readiness_source_artifact_state as _prediction_offline_readiness_source_artifact_state,
    _prediction_offline_readiness_source_state_count_issue as _prediction_offline_readiness_source_state_count_issue,
    _prediction_offline_readiness_source_state_count_issues as _prediction_offline_readiness_source_state_count_issues,
    _prediction_offline_readiness_source_url_audit_flag_issues as _prediction_offline_readiness_source_url_audit_flag_issues,
    _prediction_offline_readiness_verify_run_metadata as _prediction_offline_readiness_verify_run_metadata,
    _prediction_readiness_backfill_plan_sample_source_state as _prediction_readiness_backfill_plan_sample_source_state,
    _prediction_readiness_backfill_plan_source_state as _prediction_readiness_backfill_plan_source_state,
    _prediction_readiness_backfill_plan_source_state_for_run_metadata as _prediction_readiness_backfill_plan_source_state_for_run_metadata,
    _prediction_readiness_backfill_plan_steps as _prediction_readiness_backfill_plan_steps,
    _prediction_readiness_benchmark_backtest_source_coverage as _prediction_readiness_benchmark_backtest_source_coverage,
    _prediction_readiness_benchmark_eval_cutoff_audit as _prediction_readiness_benchmark_eval_cutoff_audit,
    _prediction_readiness_benchmark_inventory_feature_source_coverage as _prediction_readiness_benchmark_inventory_feature_source_coverage,
    _prediction_readiness_benchmark_inventory_source_coverage as _prediction_readiness_benchmark_inventory_source_coverage,
    _prediction_readiness_benchmark_source_state as _prediction_readiness_benchmark_source_state,
    _prediction_readiness_benchmark_source_url_audit_gaps as _prediction_readiness_benchmark_source_url_audit_gaps,
    _prediction_readiness_benchmark_summary as _prediction_readiness_benchmark_summary,
    _prediction_readiness_blocked_steps_by_missing_requirement as _prediction_readiness_blocked_steps_by_missing_requirement,
    _prediction_readiness_blocker_summary as _prediction_readiness_blocker_summary,
    _prediction_readiness_component_blocker_counts as _prediction_readiness_component_blocker_counts,
    _prediction_readiness_congress_load_requirement_blockers as _prediction_readiness_congress_load_requirement_blockers,
    _prediction_readiness_congress_load_source_state as _prediction_readiness_congress_load_source_state,
    _prediction_readiness_enrich_runtime_row as _prediction_readiness_enrich_runtime_row,
    _prediction_readiness_env_consistency as _prediction_readiness_env_consistency,
    _prediction_readiness_env_preflight_summary as _prediction_readiness_env_preflight_summary,
    _prediction_readiness_env_preflight_verify_summary as _prediction_readiness_env_preflight_verify_summary,
    _prediction_readiness_env_unlock_priority as _prediction_readiness_env_unlock_priority,
    _prediction_readiness_eval_window_run_archive_summary as _prediction_readiness_eval_window_run_archive_summary,
    _prediction_readiness_eval_window_run_label_gate_summary as _prediction_readiness_eval_window_run_label_gate_summary,
    _prediction_readiness_eval_window_run_source_state as _prediction_readiness_eval_window_run_source_state,
    _prediction_readiness_eval_window_run_strict_gate_summary as _prediction_readiness_eval_window_run_strict_gate_summary,
    _prediction_readiness_eval_window_run_summary as _prediction_readiness_eval_window_run_summary,
    _prediction_readiness_local_input_summaries as _prediction_readiness_local_input_summaries,
    _prediction_readiness_local_input_summary as _prediction_readiness_local_input_summary,
    _prediction_readiness_next_actions_by_kind as _prediction_readiness_next_actions_by_kind,
    _prediction_readiness_next_live_actions as _prediction_readiness_next_live_actions,
    _prediction_readiness_operator_resume_batches as _prediction_readiness_operator_resume_batches,
    _prediction_readiness_runtime_summary as _prediction_readiness_runtime_summary,
    _prediction_readiness_source_family_ids_valid as _prediction_readiness_source_family_ids_valid,
    _prediction_readiness_unlock_sequence_by_requirement_set as _prediction_readiness_unlock_sequence_by_requirement_set,
    _prediction_readiness_unlock_sequence_sort_key as _prediction_readiness_unlock_sequence_sort_key,
    _prediction_readiness_unlock_summary_by_missing_requirement as _prediction_readiness_unlock_summary_by_missing_requirement,
    _prediction_resume_script_batch_contract_issues as _prediction_resume_script_batch_contract_issues,
    _prediction_resume_script_batches as _prediction_resume_script_batches,
    _prediction_resume_script_bytes as _prediction_resume_script_bytes,
    _prediction_resume_script_clean_string_list as _prediction_resume_script_clean_string_list,
    _prediction_resume_script_env_requirements as _prediction_resume_script_env_requirements,
    _prediction_resume_script_missing_env_guard_failures as _prediction_resume_script_missing_env_guard_failures,
    _prediction_resume_script_readiness_verify_state as _prediction_resume_script_readiness_verify_state,
    _prediction_resume_script_secret_literal_failures as _prediction_resume_script_secret_literal_failures,
    _prediction_resume_script_unsafe_command_failures as _prediction_resume_script_unsafe_command_failures,
    _prediction_resume_script_verify_run_metadata as _prediction_resume_script_verify_run_metadata,
    _readiness_blocker_summary_total as _readiness_blocker_summary_total,
    _validate_prediction_offline_readiness_run_metadata as _validate_prediction_offline_readiness_run_metadata,
    _with_prediction_readiness_provenance as _with_prediction_readiness_provenance,
    _write_prediction_resume_script as _write_prediction_resume_script,
)
from src.runtime.commands.operator_reports import (
    _load_operator_handoff_payload as _load_operator_handoff_payload,
    _operator_bill_sponsor_availability_core as _operator_bill_sponsor_availability_core,
    _operator_bill_sponsor_availability_line as _operator_bill_sponsor_availability_line,
    _operator_bill_sponsor_availability_source_state as _operator_bill_sponsor_availability_source_state,
    _operator_bill_sponsor_availability_source_state_issues as _operator_bill_sponsor_availability_source_state_issues,
    _operator_bill_sponsor_availability_transitive_source_state as _operator_bill_sponsor_availability_transitive_source_state,
    _operator_congress_load_core as _operator_congress_load_core,
    _operator_congress_load_source_state as _operator_congress_load_source_state,
    _operator_cutoff_audit_core as _operator_cutoff_audit_core,
    _operator_cutoff_audit_source_state as _operator_cutoff_audit_source_state,
    _operator_cutoff_audit_source_state_count_issues as _operator_cutoff_audit_source_state_count_issues,
    _operator_cutoff_audit_transitive_source_state as _operator_cutoff_audit_transitive_source_state,
    _operator_eval_window_run_archive_lines as _operator_eval_window_run_archive_lines,
    _operator_eval_window_run_archive_source_state as _operator_eval_window_run_archive_source_state,
    _operator_eval_window_run_archive_source_state_issues as _operator_eval_window_run_archive_source_state_issues,
    _operator_eval_window_run_label_gate_source_state as _operator_eval_window_run_label_gate_source_state,
    _operator_eval_window_run_strict_gate_lines as _operator_eval_window_run_strict_gate_lines,
    _operator_handoff_bill_sponsor_availability as _operator_handoff_bill_sponsor_availability,
    _operator_handoff_check_env_preflight_source as _operator_handoff_check_env_preflight_source,
    _operator_handoff_check_resume_links as _operator_handoff_check_resume_links,
    _operator_handoff_congress_load as _operator_handoff_congress_load,
    _operator_handoff_cutoff_audit as _operator_handoff_cutoff_audit,
    _operator_handoff_eval_window_run as _operator_handoff_eval_window_run,
    _operator_handoff_jurisdiction_topology as _operator_handoff_jurisdiction_topology,
    _operator_handoff_load_readiness_summary as _operator_handoff_load_readiness_summary,
    _operator_handoff_next_actions_by_kind as _operator_handoff_next_actions_by_kind,
    _operator_handoff_plan as _operator_handoff_plan,
    _operator_handoff_resume_batch_contract_issues as _operator_handoff_resume_batch_contract_issues,
    _operator_handoff_secret_literal_failures as _operator_handoff_secret_literal_failures,
    _operator_handoff_source_url_audit as _operator_handoff_source_url_audit,
    _operator_jurisdiction_topology_core as _operator_jurisdiction_topology_core,
    _operator_jurisdiction_topology_lines as _operator_jurisdiction_topology_lines,
    _operator_jurisdiction_topology_source_state as _operator_jurisdiction_topology_source_state,
    _operator_jurisdiction_topology_source_state_issues as _operator_jurisdiction_topology_source_state_issues,
    _operator_jurisdiction_topology_transitive_source_state as _operator_jurisdiction_topology_transitive_source_state,
    _operator_runbook_secret_literal_failures as _operator_runbook_secret_literal_failures,
    _operator_runbook_verified_artifact_missing as _operator_runbook_verified_artifact_missing,
    _operator_source_url_audit_lines as _operator_source_url_audit_lines,
    _operator_source_url_audit_source_state as _operator_source_url_audit_source_state,
    _operator_source_url_audit_source_state_issues as _operator_source_url_audit_source_state_issues,
    _operator_source_url_audit_transitive_source_state as _operator_source_url_audit_transitive_source_state,
    _operator_status_batches as _operator_status_batches,
    _operator_status_canonical_sample_source_state as _operator_status_canonical_sample_source_state,
    _operator_status_canonical_transitive_source_state as _operator_status_canonical_transitive_source_state,
    _operator_status_core as _operator_status_core,
    _operator_status_count_issues as _operator_status_count_issues,
    _operator_status_non_negative_int_list as _operator_status_non_negative_int_list,
    _operator_status_plan_from_handoff as _operator_status_plan_from_handoff,
    _operator_status_sample_source_state_issues as _operator_status_sample_source_state_issues,
    _operator_status_sample_source_state_keys as _operator_status_sample_source_state_keys,
    _operator_status_sorted_string_list as _operator_status_sorted_string_list,
    _operator_status_source_state_count_issues as _operator_status_source_state_count_issues,
    _operator_status_source_state_mismatch_issues as _operator_status_source_state_mismatch_issues,
    _prediction_operator_sample_scoped_id_issues as _prediction_operator_sample_scoped_id_issues,
)
from src.runtime.commands.operator_packet import (
    _handle_prediction_operator_packet_export as _handle_prediction_operator_packet_export,
    _handle_prediction_operator_packet_manifest as _handle_prediction_operator_packet_manifest,
    _handle_prediction_operator_resume_plan as _handle_prediction_operator_resume_plan,
    _handle_prediction_operator_status as _handle_prediction_operator_status,
    _handle_verify_prediction_operator_handoff as _handle_verify_prediction_operator_handoff,
    _handle_verify_prediction_operator_packet_directory as _handle_verify_prediction_operator_packet_directory,
    _handle_verify_prediction_operator_packet_export as _handle_verify_prediction_operator_packet_export,
    _handle_verify_prediction_operator_packet_manifest as _handle_verify_prediction_operator_packet_manifest,
    _handle_verify_prediction_operator_resume_plan as _handle_verify_prediction_operator_resume_plan,
    _handle_verify_prediction_operator_resume_run as _handle_verify_prediction_operator_resume_run,
    _handle_verify_prediction_operator_runbook as _handle_verify_prediction_operator_runbook,
    _handle_verify_prediction_operator_status as _handle_verify_prediction_operator_status,
    _load_json_packet_payload as _load_json_packet_payload,
    _operator_packet_add_file as _operator_packet_add_file,
    _operator_packet_checksums_content_matches as _operator_packet_checksums_content_matches,
    _operator_packet_dedupe_files as _operator_packet_dedupe_files,
    _operator_packet_export_count_issues as _operator_packet_export_count_issues,
    _operator_packet_export_filename as _operator_packet_export_filename,
    _operator_packet_export_secret_literal_failures as _operator_packet_export_secret_literal_failures,
    _operator_packet_export_source_state_count_issues as _operator_packet_export_source_state_count_issues,
    _operator_packet_export_source_state_mismatch_issues as _operator_packet_export_source_state_mismatch_issues,
    _operator_packet_file_sha256_state as _operator_packet_file_sha256_state,
    _operator_packet_manifest_core as _operator_packet_manifest_core,
    _operator_packet_manifest_count_issues as _operator_packet_manifest_count_issues,
    _operator_packet_manifest_source_state_count_issues as _operator_packet_manifest_source_state_count_issues,
    _operator_packet_manifest_source_state_mismatch_issues as _operator_packet_manifest_source_state_mismatch_issues,
    _operator_packet_recorded_sha256_invalid as _operator_packet_recorded_sha256_invalid,
    _operator_packet_secret_literal_failures as _operator_packet_secret_literal_failures,
    _prediction_operator_env_source as _prediction_operator_env_source,
    _prediction_operator_finalize_resume_phase as _prediction_operator_finalize_resume_phase,
    _prediction_operator_handoff_runbook_text as _prediction_operator_handoff_runbook_text,
    _prediction_operator_packet_bill_sponsor_availability as _prediction_operator_packet_bill_sponsor_availability,
    _prediction_operator_packet_checksums_text as _prediction_operator_packet_checksums_text,
    _prediction_operator_packet_congress_load as _prediction_operator_packet_congress_load,
    _prediction_operator_packet_cutoff_audit as _prediction_operator_packet_cutoff_audit,
    _prediction_operator_packet_eval_window_run as _prediction_operator_packet_eval_window_run,
    _prediction_operator_packet_export_bill_sponsor_availability as _prediction_operator_packet_export_bill_sponsor_availability,
    _prediction_operator_packet_export_congress_load as _prediction_operator_packet_export_congress_load,
    _prediction_operator_packet_export_eval_window_run as _prediction_operator_packet_export_eval_window_run,
    _prediction_operator_packet_export_jurisdiction_topology as _prediction_operator_packet_export_jurisdiction_topology,
    _prediction_operator_packet_export_readme as _prediction_operator_packet_export_readme,
    _prediction_operator_packet_export_source_url_audit as _prediction_operator_packet_export_source_url_audit,
    _prediction_operator_packet_export_status_path as _prediction_operator_packet_export_status_path,
    _prediction_operator_packet_jurisdiction_topology as _prediction_operator_packet_jurisdiction_topology,
    _prediction_operator_packet_operator_status_path as _prediction_operator_packet_operator_status_path,
    _prediction_operator_packet_resume_script_path as _prediction_operator_packet_resume_script_path,
    _prediction_operator_packet_source_url_audit as _prediction_operator_packet_source_url_audit,
    _prediction_operator_packet_standalone_resume_planner as _prediction_operator_packet_standalone_resume_planner,
    _prediction_operator_packet_standalone_resume_runner as _prediction_operator_packet_standalone_resume_runner,
    _prediction_operator_packet_standalone_resume_runner_verifier as _prediction_operator_packet_standalone_resume_runner_verifier,
    _prediction_operator_packet_standalone_verifier as _prediction_operator_packet_standalone_verifier,
    _prediction_operator_resume_plan_canonical_sample_source_state as _prediction_operator_resume_plan_canonical_sample_source_state,
    _prediction_operator_resume_plan_core as _prediction_operator_resume_plan_core,
    _prediction_operator_resume_plan_count_issues as _prediction_operator_resume_plan_count_issues,
    _prediction_operator_resume_plan_count_shape_issues as _prediction_operator_resume_plan_count_shape_issues,
    _prediction_operator_resume_plan_non_negative_int_list as _prediction_operator_resume_plan_non_negative_int_list,
    _prediction_operator_resume_plan_sample_source_state_issues as _prediction_operator_resume_plan_sample_source_state_issues,
    _prediction_operator_resume_plan_source_artifact_sha256_invalid as _prediction_operator_resume_plan_source_artifact_sha256_invalid,
    _prediction_operator_resume_plan_source_artifact_sha256_matches as _prediction_operator_resume_plan_source_artifact_sha256_matches,
    _prediction_operator_resume_plan_source_state_count_issues as _prediction_operator_resume_plan_source_state_count_issues,
    _prediction_operator_resume_plan_source_state_mismatch_issues as _prediction_operator_resume_plan_source_state_mismatch_issues,
    _prediction_operator_resume_plan_valid_sample_source_state_keys as _prediction_operator_resume_plan_valid_sample_source_state_keys,
    _prediction_operator_resume_plan_verification_flags_match as _prediction_operator_resume_plan_verification_flags_match,
    _prediction_operator_resume_script_plan as _prediction_operator_resume_script_plan,
    _write_prediction_operator_handoff_runbook as _write_prediction_operator_handoff_runbook,
)
from src.runtime.commands.registry import (
    COMMAND_REGISTRY as COMMAND_REGISTRY,
    dispatch_command as dispatch_command,
)

_SUBMODULE_NAMES = (
    "_shared",
    "statements",
    "fec",
    "disclosures",
    "history",
    "runtime_env",
    "core",
    "bill_semantics",
    "prediction_misc",
    "prediction_eval",
    "prediction_eval_windows",
    "prediction_benchmark",
    "prediction_readiness",
    "operator_reports",
    "operator_packet",
    "registry",
)


class _PatchForwardingModule(_types.ModuleType):
    """Forward attribute assignment on the package to its submodules.

    For most of its life this package was a single module, and tests patch
    collaborators at ``src.runtime.commands.<name>`` (``mock.patch`` /
    ``monkeypatch``). After the split each function resolves globals in its
    own submodule, so a plain assignment on the package would no longer reach
    call sites. Forwarding ``__setattr__`` to every submodule that defines the
    name preserves the monolith's patching contract; ``mock.patch`` restores
    the original through the same path on exit.
    """

    def __setattr__(self, name: str, value: object) -> None:
        super().__setattr__(name, value)
        for sub_name in _SUBMODULE_NAMES:
            sub = _sys.modules.get(f"{__name__}.{sub_name}")
            if sub is not None and name in sub.__dict__:
                _types.ModuleType.__setattr__(sub, name, value)


_sys.modules[__name__].__class__ = _PatchForwardingModule
