from __future__ import annotations

from src.ontology import (
    ONTOLOGY_AGENT_TOOL_CONTRACT_VERSION,
    ONTOLOGY_AGENT_TOOL_MANIFEST_VERSION,
    ONTOLOGY_FRONTEND_CLIENT_VERSION,
    ONTOLOGY_FRONTEND_CONTRACT_VERSION,
    ONTOLOGY_FRONTEND_INDEX_VERSION,
    ONTOLOGY_STATIC_SCHEMA_VERSION,
)
from src.ontology.agent_tools import (
    ONTOLOGY_AGENT_TOOL_CONTRACT_VERSION as AGENT_TOOL_CONTRACT_VERSION,
)
from src.ontology.agent_tools import (
    ONTOLOGY_AGENT_TOOL_MANIFEST_VERSION as AGENT_TOOL_MANIFEST_VERSION,
)
from src.ontology.frontend_contracts import (
    ONTOLOGY_FRONTEND_CLIENT_VERSION as FRONTEND_CLIENT_VERSION,
)
from src.ontology.frontend_contracts import (
    ONTOLOGY_FRONTEND_CONTRACT_VERSION as FRONTEND_CONTRACT_VERSION,
)
from src.ontology.static_schema import (
    ONTOLOGY_FRONTEND_INDEX_VERSION as FRONTEND_INDEX_VERSION,
)
from src.ontology.static_schema import ONTOLOGY_STATIC_SCHEMA_VERSION as STATIC_SCHEMA_VERSION
from src.ontology.versions import (
    ONTOLOGY_AGENT_TOOL_CONTRACT_VERSION as CANONICAL_AGENT_TOOL_CONTRACT_VERSION,
)


def test_ontology_versions_are_canonical_reexports() -> None:
    assert ONTOLOGY_STATIC_SCHEMA_VERSION == STATIC_SCHEMA_VERSION
    assert ONTOLOGY_FRONTEND_INDEX_VERSION == FRONTEND_INDEX_VERSION
    assert ONTOLOGY_FRONTEND_CONTRACT_VERSION == FRONTEND_CONTRACT_VERSION
    assert ONTOLOGY_FRONTEND_CLIENT_VERSION == FRONTEND_CLIENT_VERSION
    assert ONTOLOGY_AGENT_TOOL_MANIFEST_VERSION == AGENT_TOOL_MANIFEST_VERSION
    assert ONTOLOGY_AGENT_TOOL_CONTRACT_VERSION == AGENT_TOOL_CONTRACT_VERSION


def test_agent_tool_contract_version_tracks_frontend_contract_version() -> None:
    assert CANONICAL_AGENT_TOOL_CONTRACT_VERSION == ONTOLOGY_FRONTEND_CONTRACT_VERSION
